# Generated by Django 6.0 on 2026-01-05 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('categoriaUsuario', models.CharField(blank=True, max_length=50, null=True)),
                ('user_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField()),
                ('desc_evento', models.CharField(max_length=100)),
                ('desc_area', models.CharField(max_length=100)),
                ('desc_leitor', models.CharField(max_length=100)),
                ('ent_sai', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='smartcard.usuario', to_field='matricula')),
            ],
            options={
                'unique_together': {('usuario', 'data_acesso', 'desc_evento', 'desc_area', 'ent_sai')},
            },
        ),
    ]
