# Generated by Django 6.0 on 2026-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_auth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
