# Generated by Django 5.2 on 2026-01-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0003_alter_usuario_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_auth',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
